import { NextResponse } from 'next/server'
import clientPromise from '@/lib/mongodb'

type Recommendation = 'Strong Hire' | 'Hire' | 'Weak Hire'

interface FinalVerdict {
  summary: string
  strengths: string[]
  improvements: string[]
  recommendation: Recommendation
  generated_at: Date
  model: string // Allow any model name that works
}

/**
 * GET verdict - Only fetches from database
 * Verdicts are generated automatically by background worker
 */
export async function GET(
  request: Request,
  context: { params: Promise<{ student_uid: string }> }
) {
  try {
    const { student_uid } = await context.params
    console.log('Fetching verdict for student_uid:', student_uid)

    const client = await clientPromise
    const db = client.db('student_dashboard')

    // Check if AI-generated verdict already exists in final_verdicts collection
    const existing = await db
      .collection('final_verdicts')
      .findOne<FinalVerdict & { student_uid: string }>(
        { student_uid }
      )

    console.log('Existing verdict check:', existing ? 'Found in final_verdicts' : 'Not found')

    // If verdict exists, return it immediately
    if (existing) {
      console.log('Returning existing verdict from final_verdicts collection')
      // Remove student_uid from response (it's just for DB lookup)
      const { student_uid: _, ...verdict } = existing
      return NextResponse.json({
        status: 'ok',
        data: verdict,
      })
    }

    // No verdict found - return null (verdicts are generated by background worker)
    console.log('No existing verdict found. Verdict will be generated by background worker.')
    return NextResponse.json({
      status: 'ok',
      data: null,
      message: 'Verdict not yet generated. Please wait for background sync.',
    })
  } catch (error: any) {
    console.error('Error fetching verdict:', error)
    return NextResponse.json(
      { 
        status: 'error', 
        message: error.message || 'Internal server error',
      },
      { status: 500 }
    )
  }
}

/**
 * POST verdict - Legacy endpoint for manual verdict updates
 * (Not used for AI generation - that's done by background worker)
 */
export async function POST(
  request: Request,
  context: { params: Promise<{ student_uid: string }> }
) {
  try {
    const { student_uid } = await context.params
    const body = await request.json()

    const client = await clientPromise
    const db = client.db('student_dashboard')

    const verdict = {
      student_uid,
      decision: body.decision || '', // 'Accepted', 'Rejected', 'Hold'
      comments: body.comments || '',
      internal_review: body.internal_review || '',
      reviewer_name: body.reviewer_name || '',
      assessment_notes: body.assessment_notes || '',
      tr1_notes: body.tr1_notes || '',
      tr2_notes: body.tr2_notes || '',
      timestamps: {
        created_at: new Date(),
        updated_at: new Date(),
      },
    }

    await db.collection('final_verdicts').updateOne(
      { student_uid },
      { $set: verdict },
      { upsert: true }
    )

    return NextResponse.json({
      status: 'ok',
      data: verdict,
    })
  } catch (error: any) {
    console.error('Error saving verdict:', error)
    return NextResponse.json(
      { status: 'error', message: error.message },
      { status: 500 }
    )
  }
}
